### ISSUE TITLE
Big SVG files fills whole editor window

### ISSUE THREAD

**Issue by netsi1964** [peterflynn/svg-preview#14]
If you open a SVG element with say a A4 size, the whole editor is filled with the preview.
The Zoom panel is not visible, so you cannot zoom out.
If you then set file type to XML (or other) the file is still forced to your SVG preview.

Please make panel position accessable  even with big SVG files.
And perhaps: If user chooses another file type you preview should not render.

**Comment by SaraSoueidan** [comment]
I can confirm and support this. This is the main reason why I need to switch to Sublime in some cases.

**Comment by peterflynn** [comment]
@netsi1964 @SaraSoueidan Fixed in 1.3 -- the height is now limited to 3/4 of the window size, which should for all practical purposes make this impossible to hit.

1.3 also includes some great improvements to width/height/viewBox handling thanks to PR #13.

**Comment by netsi1964** [comment]
Great job @peterflynn ! :-) It looks great. Did you just add option to click on SVG preview to select XML node in editor? Or did I miss that one - anyway, great idea. Thanks.

**Comment by peterflynn** [comment]
That clicking feature was there in 1.2 too. Thanks though! :-)
