### ISSUE TITLE
can i change the color when i select the coding 

### ISSUE THREAD

**Issue by semi-xi** [peterflynn/svg-preview#15]
can i change the color when i select the coding  and how to change it? which css style

**Comment by peterflynn** [comment]
Are you talking about changing the appearance of a specific SVG image you're working with?  Or changing the color of parts of the Brackets UI?

Anywhere there is a color value defined in your code, you can put your cursor there and press Ctrl-E to open a color picker.  (That's a built-in Brackets feature -- you don't need SVG Preview to use it).

**Comment by peterflynn** [comment]
Closing since it's not clear there's any problem here
