### ISSUE TITLE
Opening a svg file exported from Illustrator causes Brackets layout not to render correctly.

### ISSUE THREAD

**Issue by RaymondLim** [peterflynn/svg-preview#3]
Copy https://gist.github.com/RaymondLim/8000990 and save it as a new svg file in your current project in Brackets.

svg viewer shows up without the toolbar. If you select it from project tree, then you will see an area of white spaces at the bottom of the project tree and selection highlight is no longer aligned with the triangle pointed to the editor.

**Comment by peterflynn** [comment]
I believe this is the same issue as #14, so it should be fixed in 1.3 now.
