### ISSUE TITLE
Viewer is too small when svg height and width are defined as cm units

### ISSUE THREAD

**Issue by lkcampbell** [peterflynn/svg-preview#8]
**OS:** Mac OSX Mavericks

**Brackets Version:** sprint 38 experimental build 0.38.0-12606 (release 4df8afdad)

**Extension Version:** 1.1.2

**Repro  Steps:**
  1. Open a SVG file with the following content (a W3C spec example): https://gist.github.com/lkcampbell/f12f06746602a83cc8af

**Expected Results:**
Should be able to see the entire SVG file.

**Observed Results:**
The height and width of the SVG viewer are too small to see the full image.

**Other Notes:**
Changing the height and width to bigger numbers, with no units or pixel units, makes the SVG viewer larger.

**Comment by peterflynn** [comment]
Fixed in 1.3 thanks to @AmeliaBR!

**Comment by lkcampbell** [comment]
Confirmed as fixed, thanks.
